name: ddps
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.10.9
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - addict==2.4.0
    - appdirs==1.4.4
    - awscli==1.27.89
    - boto3==1.26.89
    - botocore==1.29.89
    - charset-normalizer==3.1.0
    - cityscapesscripts==2.2.1
    - colorama==0.4.4
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - docutils==0.16
    - einops==0.6.0
    - environs==9.5.0
    - filelock==3.9.0
    - fonttools==4.39.0
    - huggingface-hub==0.13.1
    - humanfriendly==10.0
    - humanize==4.6.0
    - idna==3.4
    - jmespath==1.0.1
    - kiwisolver==1.4.4
    - marshmallow==3.19.0
    - matplotlib==3.7.1
    - mmcls==0.25.0
    - mmcv-full==1.7.0
    - mmdet==2.28.2
    - mmsegmentation==0.30.0
    - multiprocessing-logging==0.3.4
    - multiscaledeformableattention==1.0
    - numpy==1.24.2
    - opencv-python==4.7.0.72
    - packaging==23.0
    - petrel-oss-sdk==v2.2.1-2-g1505ef3-master
    - pillow==9.4.0
    - prettytable==3.6.0
    - pyasn1==0.4.8
    - pycocotools==2.0.6
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pyyaml==5.4.1
    - requests==2.28.2
    - rsa==4.7.2
    - s3transfer==0.6.0
    - scipy==1.10.1
    - six==1.16.0
    - terminaltables==3.1.10
    - timm==0.6.12
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.65.0
    - typing==3.7.4.3
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wcwidth==0.2.6
    - yapf==0.32.0

